import pandas as pd

eng_dict = {'segrar': 'wins',
            'starter': 'starts',
            'proc': 'procent',
            'bankod': 'circuitcode',
            'bana': 'circuit',
            'avstand': 'distance',
            'systemnr': 'systemnumber',
            'rad': 'row',
            'beskr': 'description',
            'msegrar': 'mwins',
            'mstarter': 'mwins',
            'mproc': 'mprocent',
            'namn': 'name',
            'intakt': 'earnings',
            'intaktii': 'earningsii',
            'intaktperstart': 'earningperstart',
            'pliar': 'plthisyear',
            'pliar2': 'plthisyear2',
            'pliar3': 'plthisyear3',
            'starteriar': 'startsthisyear',
            'hemmabana': 'homecircuit',
            'v75segrar': 'v75wins',
            'v75starter': 'v75starts',
            'v75proc': 'v75procent',
            'hingstid': 'stallionid',
            'morfarid': 'mothersfatherid',
            'tranarid': 'coachid',
            'agarid': 'ownerid',
            'nyckel': 'key',
            'aktiverad': 'activated',
            'tvlid': 'compid',
            'spar': 'track',
            'kommentar': 'comment',
            'antal': 'amount',
            'vinster': 'wins',
            'plats': 'place',
            'snittodds': 'averageodds',
            'vinstkr': 'winkr',
            'vinstkrsort': 'winkrtype',
            'totantal': 'totalamount',
            'totvinster': 'totalwins',
            'totproc': 'totalproc',
            'kommentar1': 'comment1',
            'kommentar2': 'comment2',
            'kommid': 'commentid',
            'varde': 'value',
            'numplac': 'numberplace',
            'bana': 'circuit',
            'kusk': 'driver',
            'atgkod': 'atgcode',
            'kortnamn': 'shortname',
            'hembana': 'homecircuit',
            'datum': 'date',
            'lopp': 'race',
            'distans': 'distance',
            'tillag': 'addition',
            'placering': 'placement',
            'tid': 'time',
            'senaste': 'latest',
            'besta': 'best', #Assuming correct
            'anm': 'note',
            'typ': 'type',
            'pris1': 'price1',
            'stabilitet': 'stability',
            'bort': 'away',
            'agarnr': 'ownernr',
            'tranarnr': 'coachnr',
            'uppehall': 'break',
            'ant': 'amount',
            'pris': 'price',
            'vinst': 'win',
            'spikar': 'spikes',
            'spiktyp': 'spiketype',
            'maxhastar': 'maxhorses',
            'spikratt': 'spikecorrect',
            'startsatt': 'started',
            'banforh': 'circuitcondition',
            'forstapris': 'firstprice',
            'loppid': 'circuitid'
}


def read_table(path, columns,header=None, nrows=None, **kwargs):
    df = pd.read_csv(path,  header=header, sep='\t', nrows=nrows, encoding='latin-1',
                     error_bad_lines=False, na_values=['\\N'],
                     **kwargs)
    df.columns = columns
    return df